"""initial_schema

Revision ID: a9ed29c6b953
Revises: 
Create Date: 2026-04-01 10:12:39.340566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ed29c6b953'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_active_for_duties', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('support_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('draft','final')", name='ck_daily_report_status'),
    sa.ForeignKeyConstraint(['support_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'support_user_id', name='uq_daily_report_date_employee')
    )
    op.create_index(op.f('ix_daily_reports_date'), 'daily_reports', ['date'], unique=False)
    op.create_index(op.f('ix_daily_reports_status'), 'daily_reports', ['status'], unique=False)
    op.create_index(op.f('ix_daily_reports_support_user_id'), 'daily_reports', ['support_user_id'], unique=False)
    op.create_table('duty_assignments',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('support_user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('slot >= 0 AND slot <= 10', name='ck_duty_slot_range'),
    sa.ForeignKeyConstraint(['support_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('date', 'slot')
    )
    op.create_table('duty_swap_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('from_slot', sa.Integer(), nullable=False),
    sa.Column('to_slot', sa.Integer(), nullable=False),
    sa.Column('requester_user_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending','accepted','rejected')", name='ck_swap_status'),
    sa.CheckConstraint('from_slot >= 0 AND from_slot <= 10', name='ck_swap_from_slot_range'),
    sa.CheckConstraint('to_slot >= 0 AND to_slot <= 10', name='ck_swap_to_slot_range'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duty_swap_requests_created_at'), 'duty_swap_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_duty_swap_requests_date'), 'duty_swap_requests', ['date'], unique=False)
    op.create_index(op.f('ix_duty_swap_requests_requester_user_id'), 'duty_swap_requests', ['requester_user_id'], unique=False)
    op.create_index(op.f('ix_duty_swap_requests_status'), 'duty_swap_requests', ['status'], unique=False)
    op.create_index(op.f('ix_duty_swap_requests_target_user_id'), 'duty_swap_requests', ['target_user_id'], unique=False)
    op.create_table('report_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['daily_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_entries_report_id'), 'report_entries', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_entries_report_id'), table_name='report_entries')
    op.drop_table('report_entries')
    op.drop_index(op.f('ix_duty_swap_requests_target_user_id'), table_name='duty_swap_requests')
    op.drop_index(op.f('ix_duty_swap_requests_status'), table_name='duty_swap_requests')
    op.drop_index(op.f('ix_duty_swap_requests_requester_user_id'), table_name='duty_swap_requests')
    op.drop_index(op.f('ix_duty_swap_requests_date'), table_name='duty_swap_requests')
    op.drop_index(op.f('ix_duty_swap_requests_created_at'), table_name='duty_swap_requests')
    op.drop_table('duty_swap_requests')
    op.drop_table('duty_assignments')
    op.drop_index(op.f('ix_daily_reports_support_user_id'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_status'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_date'), table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
